sudo: required
services:
    - docker

before_install:
    - docker build -t franck20/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true franck20/react-test npm test

after_success:
    - docker build -t franck20/multi-client ./client
    - docker build -t franck20/multi-nginx ./nginx
    - docker build -t franck20/multi-server ./server
    - docker build -t franck20/multi-worker ./worker
    # before push to docker hub is need log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push franck20/multi-client
    - docker push franck20/multi-nginx
    - docker push franck20/multi-server
    - docker push franck20/multi-worker